version: '3.8'

services:
    api:
        image: api
        build: .
        volumes: 
            - .:/api
        ports:
            - 5000:5000
        depends_on:
            - database
    database:
        image: mongo
        ports:
            - 27017:27017
    redis:
        image: redis
        ports:
            - 6379:6379
